/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TrainerApp;

/**
 *
 * @author x12342071
 */
public class ListOfClasses extends javax.swing.JFrame {

    /**
     * Creates new form ListOfClasses
     */
    public ListOfClasses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MonSpinBTN = new javax.swing.JButton();
        MonKBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TuesBoxBTN = new javax.swing.JButton();
        TuesTRXBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        WedBoxBTN = new javax.swing.JButton();
        WedKBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ThurAerBTN = new javax.swing.JButton();
        ThurSpinBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        FriCFBTN = new javax.swing.JButton();
        FriTRXBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        HomeBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Class List");

        jLabel2.setText("Monday");

        MonSpinBTN.setText("Spinning 17:00-18:00");
        MonSpinBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonSpinBTNActionPerformed(evt);
            }
        });

        MonKBTN.setText("Kettle Bells 18:00-19:00");
        MonKBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonKBTNActionPerformed(evt);
            }
        });

        jLabel3.setText("Tuesday");

        TuesBoxBTN.setText("Boxercise 17:00-18:00");
        TuesBoxBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesBoxBTNActionPerformed(evt);
            }
        });

        TuesTRXBTN.setText("TRX 18:00-19:00");
        TuesTRXBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesTRXBTNActionPerformed(evt);
            }
        });

        jLabel4.setText("Wednesday");

        WedBoxBTN.setText("Boxercise 17:00-18:00");
        WedBoxBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WedBoxBTNActionPerformed(evt);
            }
        });

        WedKBTN.setText("Kettle Bells 18:00-19:00");
        WedKBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WedKBTNActionPerformed(evt);
            }
        });

        jLabel5.setText("Thursday");

        ThurAerBTN.setText("Aerobics 17:00-18:00");
        ThurAerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThurAerBTNActionPerformed(evt);
            }
        });

        ThurSpinBTN.setText("Spinning 18:00-19:00");
        ThurSpinBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThurSpinBTNActionPerformed(evt);
            }
        });

        jLabel6.setText("Friday");

        FriCFBTN.setText("Cross fit and abs 17:00-18:00");
        FriCFBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriCFBTNActionPerformed(evt);
            }
        });

        FriTRXBTN.setText("TRX 18:00-19:00");
        FriTRXBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriTRXBTNActionPerformed(evt);
            }
        });

        BackBTN.setText("Back");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        HomeBTN.setText("Home");
        HomeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MonKBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MonSpinBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TuesBoxBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TuesTRXBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WedKBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThurAerBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThurSpinBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FriCFBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FriTRXBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WedBoxBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel6)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(BackBTN)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeBTN))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HomeBTN)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BackBTN)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(MonSpinBTN)
                .addGap(10, 10, 10)
                .addComponent(MonKBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TuesBoxBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TuesTRXBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WedBoxBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WedKBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThurAerBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThurSpinBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FriCFBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FriTRXBTN)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MonSpinBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonSpinBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MondaySpin myMonSpin = new MondaySpin();
        myMonSpin.setVisible(true); //
    }//GEN-LAST:event_MonSpinBTNActionPerformed

    private void MonKBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonKBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MondayKBells myMonK = new MondayKBells();
        myMonK.setVisible(true); //
    }//GEN-LAST:event_MonKBTNActionPerformed

    private void TuesBoxBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesBoxBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TuesdayBox myTuesBox = new TuesdayBox();
        myTuesBox.setVisible(true); //
    }//GEN-LAST:event_TuesBoxBTNActionPerformed

    private void TuesTRXBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesTRXBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TuesdayTRX myTuesTRX = new TuesdayTRX();
        myTuesTRX.setVisible(true); //
    }//GEN-LAST:event_TuesTRXBTNActionPerformed

    private void WedBoxBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WedBoxBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        WednesdayBox myWedBox = new WednesdayBox();
        myWedBox.setVisible(true); //
    }//GEN-LAST:event_WedBoxBTNActionPerformed

    private void WedKBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WedKBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        WednesdayKBells myWedK = new WednesdayKBells();
        myWedK.setVisible(true); //
    }//GEN-LAST:event_WedKBTNActionPerformed

    private void ThurAerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThurAerBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ThursdayAerobics myThurAer = new ThursdayAerobics();
        myThurAer.setVisible(true); //
    }//GEN-LAST:event_ThurAerBTNActionPerformed

    private void ThurSpinBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThurSpinBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ThursdaySpin myThurSpin = new ThursdaySpin();
        myThurSpin.setVisible(true); //
    }//GEN-LAST:event_ThurSpinBTNActionPerformed

    private void FriCFBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriCFBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FridayCrossFit myFriCF = new FridayCrossFit();
        myFriCF.setVisible(true); //
    }//GEN-LAST:event_FriCFBTNActionPerformed

    private void FriTRXBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriTRXBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FridayTRX myFriTRX = new FridayTRX();
        myFriTRX.setVisible(true); //
    }//GEN-LAST:event_FriTRXBTNActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrainerGUI myTG = new TrainerGUI();
        myTG.setVisible(true); 
    }//GEN-LAST:event_BackBTNActionPerformed

    private void HomeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBTNActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
        GymHome myGH = new GymHome();
        myGH.setVisible(true);
    }//GEN-LAST:event_HomeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfClasses().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton FriCFBTN;
    private javax.swing.JButton FriTRXBTN;
    private javax.swing.JButton HomeBTN;
    private javax.swing.JButton MonKBTN;
    private javax.swing.JButton MonSpinBTN;
    private javax.swing.JButton ThurAerBTN;
    private javax.swing.JButton ThurSpinBTN;
    private javax.swing.JButton TuesBoxBTN;
    private javax.swing.JButton TuesTRXBTN;
    private javax.swing.JButton WedBoxBTN;
    private javax.swing.JButton WedKBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
